import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"
import Navtop from "@/components/Navtop"
import Footer from "@/components/ui/Footer"
import { Providers } from "./providers"   // ✅ notice "./providers" not "@/components/Providers"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-gradient-to-b from-[#f2e1cb]/40 to-white antialiased`}
      >
        <Providers>
          <Navtop />
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
